name: Arduino CLI build

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - ".github/workflows/build_arduino.yml"
      - "examples/**"

  push:
    paths:
      - ".github/workflows/build_arduino.yml"
      - "examples/**"

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check code formatting
        uses: per1234/artistic-style-action@main
        with:
          options-file-path: ./examples/examples_formatter.conf
          name-patterns: |
            - '*.ino'
            - '*.cpp'
            - '*.hpp'
            - '*.h'
          target-paths: |
            - examples
  build:
    needs: check_formatting
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        fqbn:
          - "arduino:avr:yun"
          - "arduino:avr:uno"
          - "arduino:avr:diecimila"
          - "arduino:avr:nano"
          - "arduino:avr:mega"
          - "arduino:avr:megaADK"
          - "arduino:avr:leonardo"
          - "arduino:avr:micro"
          - "arduino:avr:esplora"
          - "arduino:avr:mini"
          - "arduino:avr:ethernet"
          - "arduino:avr:fio"
          - "arduino:avr:bt"
          # - "arduino:avr:LilyPad"  # board not found
          - "arduino:avr:LilyPadUSB"
          - "arduino:avr:pro"
          - "arduino:avr:atmegang"
          - "arduino:avr:robotControl"
          # - "arduino:avr:gemma"   # does not support SPI
          - "arduino:avr:circuitplay32u4cat"
          - "arduino:avr:yunmini"
          - "arduino:avr:chiwawa"
          - "arduino:avr:one"
          - "arduino:avr:unowifi"
          - "arduino:mbed:nano33ble"
          - "arduino:samd:mkr1000"
          - "arduino:samd:mkrzero"
          - "arduino:samd:mkrwifi1010"
          - "arduino:samd:nano_33_iot"
          - "arduino:samd:mkrfox1200"
          - "arduino:samd:mkrwan1300"
          - "arduino:samd:mkrwan1310"
          - "arduino:samd:mkrgsm1400"
          - "arduino:samd:mkrnb1500"
          - "arduino:samd:mkrvidor4000"
          - "arduino:samd:adafruit_circuitplayground_m0"
          - "arduino:samd:mzero_pro_bl"
          - "arduino:samd:mzero_bl"
          - "arduino:samd:tian"
          - "arduino:megaavr:uno2018"
          # - "arduino:megaavr:nano4809"  # board not found

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          sketch-paths: |
            - examples/Getting_Started_SimpleClient_Mesh
            - examples/Getting_Started_SimpleServer_Mesh
            - examples/InteractiveServer_Mesh
            - examples/MQTT/mqtt_basic
            - examples/MQTT/mqtt_basic_2
            - examples/SimpleClient_Mesh
            - examples/SLIP_Gateway
            - examples/SLIP_InteractiveServer
            - examples/TAP/Getting_Started_InteractiveServer
            - examples/TAP/Getting_Started_SimpleClient
            - examples/TAP/Getting_Started_SimpleClient_DNS
            - examples/TAP/Getting_Started_SimpleServer
            - examples/TAP/Getting_Started_SimpleServer_Minimal
          # - examples/TAP/InteractiveServer  # specific to AVR boards
          # - examples/InteractiveServer_Mesh_ESPWifi  # needs ESP8266WiFi.h
          libraries: |
            - name: RF24
            - name: RF24Mesh
            - name: RF24Network
            - name: PubSubClient
            - name: MQTT
            - source-path: ./
          # - source-url: https://github.com/nRF24/RF24Network.git
          #   version: CMake-4-Linux
          # - source-url: https://github.com/nRF24/RF24Mesh.git
          #   version: CMake-4-Linux
          fqbn: ${{ matrix.fqbn }}
